# --- Configuración del Microcontrolador ---
MCU     := atmega328p
F_CPU   := 16000000UL
PROGRAMMER := usbasp

# --- Herramientas ---
CC      := avr-gcc
OBJCOPY := avr-objcopy
AVRDUDE := avrdude

# --- Banderas de Compilación ---
# -x assembler-with-cpp permite usar #include y #define en archivos .S
CFLAGS  := -mmcu=$(MCU) -DF_CPU=$(F_CPU) -x assembler-with-cpp
DFLAGS  := -ggdb3 -O0

# Target por defecto
all: release

release: main.S
	@echo "Inicializando compilación (Release)..."
	mkdir -p release
	$(CC) $(CFLAGS) -Os main.S -o release/main.elf
	$(OBJCOPY) -j .text -j .data -O ihex release/main.elf release/main.hex
	@echo "Compilación exitosa: release/main.hex preparado."

debug: main.S
	@echo "Inicializando compilación modo depuración (Debug)..."
	mkdir -p build
	$(CC) $(CFLAGS) $(DFLAGS) main.S -o build/main.elf
	@echo "Compilación exitosa: build/main.elf preparado para GDB."

# Regla para quemar el programa en el microcontrolador usando USBasp
flash: release
	@echo "Cargando firmware mediante USBasp..."
	$(AVRDUDE) -c $(PROGRAMMER) -p $(MCU) -U flash:w:release/main.hex:i

clean:
	@echo "Limpiando archivos generados..."
	rm -rf build release

.PHONY: all release debug flash clean